# Generated by Django 5.2.17 on 2026-09-25 00:41

import accounts.managers
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(choices=[('STUDENT', 'Student'), ('ADMIN', 'Administrators')], max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['role_id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=190, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending verification'), ('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('LOCKED', 'Locked')], default='ACTIVE', max_length=20)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login_at', null=True)),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('academic_year', models.CharField(blank=True, max_length=50, null=True)),
                ('monthly_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monthly_savings_goal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avatar_path', models.ImageField(blank=True, max_length=500, null=True, upload_to='avatars/%Y/%m/')),
                ('currency_code', models.CharField(default='VND', max_length=3)),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_token_hash', models.CharField(max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('reset_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_tokens',
                'indexes': [models.Index(fields=['user', 'expires_at', 'used_at'], name='idx_reset_user_expiry')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='chk_reset_expiry')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'status'], name='idx_users_role_status'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='idx_users_created_at'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('failed_login_attempts__lte', 100)), name='chk_users_failed_login'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_allowance__gte', 0)), name='chk_profiles_allowance'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_savings_goal__gte', 0)), name='chk_profiles_savings_goal'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'revoked_at', 'expires_at'], name='idx_sessions_user_active'),
        ),
        migrations.AddConstraint(
            model_name='usersession',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='chk_session_expiry'),
        ),
    ]
