# Generated by Django 5.2.17 on 2026-09-25 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('weekly_summary', 'Weekly summary'), ('monthly_summary', 'Monthly summary'), ('savings_threshold', 'Savings goal warning'), ('low_balance', 'Low balance warning')], max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('income_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expense_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('savings_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('action_path', models.CharField(default='/notifications/', max_length=500)),
                ('dedup_key', models.CharField(max_length=190, unique=True)),
                ('is_read', models.BooleanField(default=False)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='idx_notif_user_unread'), models.Index(fields=['kind', 'created_at'], name='idx_notif_kind_created')],
            },
        ),
    ]
